/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views.employee;

import javax.swing.JLabel;

/**
 *
 * @author Admin
 */
public class dayView extends javax.swing.JPanel {

    /**
     * Creates new form dayView
     */
    public dayView() {
        initComponents();
    }

    public JLabel getLabelNumber() {
        return labelNumber;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelNumber = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(60, 60));
        setMinimumSize(new java.awt.Dimension(60, 60));
        setPreferredSize(new java.awt.Dimension(60, 60));

        labelNumber.setBackground(new java.awt.Color(240, 240, 200));
        labelNumber.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelNumber.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNumber.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelNumber;
    // End of variables declaration//GEN-END:variables
}
