/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views.employee;

import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author Admin
 */
public class inforView extends javax.swing.JPanel {

    /**
     * Creates new form menuView
     */
    public inforView() {
        initComponents();
        btnChangeInfor.putClientProperty("JButton.buttonType", "roundRect");
        btnChangePass.putClientProperty("JButton.buttonType", "roundRect");
        btnHS.putClientProperty("JButton.buttonType", "roundRect");
        btnNS.putClientProperty("JButton.buttonType", "roundRect");
    }

    public JButton getBtnChangeInfor() {
        return btnChangeInfor;
    }

    public JButton getBtnChangePass() {
        return btnChangePass;
    }

    public JButton getBtnHS() {
        return btnHS;
    }

    public JButton getBtnNS() {
        return btnNS;
    }

    public JLabel getLabName() {
        return labName;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labName = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnChangePass = new javax.swing.JButton();
        btnChangeInfor = new javax.swing.JButton();
        btnNS = new javax.swing.JButton();
        btnHS = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 251, 230));
        setMinimumSize(new java.awt.Dimension(1008, 680));
        setPreferredSize(new java.awt.Dimension(1008, 680));

        labName.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        labName.setText("Xin chào Trần Đức Cường !");

        jPanel1.setBackground(new java.awt.Color(251, 133, 95));
        jPanel1.setPreferredSize(new java.awt.Dimension(170, 680));

        btnChangePass.setText("Đổi mật khẩu");

        btnChangeInfor.setText("Thay đổi thông tin");

        btnNS.setText("Năng suất");
        btnNS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNSActionPerformed(evt);
            }
        });

        btnHS.setText("Hiệu suất");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHS)
                    .addComponent(btnNS)
                    .addComponent(btnChangeInfor)
                    .addComponent(btnChangePass))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnChangeInfor, btnChangePass, btnHS, btnNS});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(btnChangePass, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(btnChangeInfor)
                .addGap(46, 46, 46)
                .addComponent(btnNS)
                .addGap(48, 48, 48)
                .addComponent(btnHS)
                .addContainerGap(239, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnChangeInfor, btnChangePass, btnHS, btnNS});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(labName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 398, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(labName)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNSActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChangeInfor;
    private javax.swing.JButton btnChangePass;
    private javax.swing.JButton btnHS;
    private javax.swing.JButton btnNS;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labName;
    // End of variables declaration//GEN-END:variables
}
